# Generated by Django 5.1.3 on 2024-11-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
