# Generated by Django 5.1.3 on 2024-12-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager_app', '0004_remove_staff_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='staff',
        ),
    ]
