# Generated by Django 5.1.3 on 2024-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager_app', '0005_remove_leave_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
