# Generated by Django 5.1.3 on 2024-12-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager_app', '0006_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='classroom_manager_app.staff'),
        ),
    ]
