# Generated by Django 5.1.3 on 2024-12-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager_app', '0007_leave_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='name',
            new_name='division',
        ),
    ]
